// Generated by scripts/normalize-catalogue.js.
module.exports = [
    {
        "from": "0xdead-2016",
        "to": "0xdead"
    },
    {
        "from": "10-years-of-game-golfing-2022",
        "to": "10-years-of-game-golfing"
    },
    {
        "from": "1257-samalas-2023",
        "to": "1257-samalas"
    },
    {
        "from": "13-blades-2024",
        "to": "13-blades"
    },
    {
        "from": "13-bubbles-2024",
        "to": "13-bubbles"
    },
    {
        "from": "13-drums-2023",
        "to": "13-drums"
    },
    {
        "from": "13-low-2024",
        "to": "13-low"
    },
    {
        "from": "13-maze",
        "to": "13-maze-2024"
    },
    {
        "from": "13-squared-2024",
        "to": "13-squared"
    },
    {
        "from": "13all-room-2024",
        "to": "13all-room"
    },
    {
        "from": "13c-defense-2023",
        "to": "13c-defense"
    },
    {
        "from": "13c-gauntlet-2024",
        "to": "13c-gauntlet"
    },
    {
        "from": "13k-solitaire-2018",
        "to": "13k-solitaire"
    },
    {
        "from": "13s-tactics",
        "to": "13s-tactics-2024"
    },
    {
        "from": "13th-barber-s-guild-2023",
        "to": "13th-barber-s-guild"
    },
    {
        "from": "13th-floor-2024",
        "to": "13th-floor"
    },
    {
        "from": "13th-gate-2024",
        "to": "13th-gate"
    },
    {
        "from": "2021-a-space-opera-2021",
        "to": "2021-a-space-opera"
    },
    {
        "from": "2048-13-2024",
        "to": "2048-13"
    },
    {
        "from": "26-games-in-1-2016",
        "to": "26-games-in-1"
    },
    {
        "from": "2ap-backyard-assault",
        "to": "2ap-backyard-assault-2019"
    },
    {
        "from": "3dc5s-2021",
        "to": "3dc5s"
    },
    {
        "from": "4-elements-tower-defense",
        "to": "4-elements-tower-defense-2014"
    },
    {
        "from": "4-offline-2018",
        "to": "4-offline"
    },
    {
        "from": "404-2020",
        "to": "404"
    },
    {
        "from": "404-bc-pinball-2020",
        "to": "404-bc-pinball"
    },
    {
        "from": "404-box-2020",
        "to": "404-box"
    },
    {
        "from": "404-flappingbird-2020",
        "to": "404-flappingbird"
    },
    {
        "from": "404-missingpage-2020",
        "to": "404-missingpage"
    },
    {
        "from": "404-orbiting-asteroids-2020",
        "to": "404-orbiting-asteroids"
    },
    {
        "from": "404-remain-not-found-2020",
        "to": "404-remain-not-found"
    },
    {
        "from": "404-search-for-the-missing-pages-2020",
        "to": "404-search-for-the-missing-pages"
    },
    {
        "from": "404-snake-monochrome-2020",
        "to": "404-snake-monochrome"
    },
    {
        "from": "404-soccer-2020",
        "to": "404-soccer"
    },
    {
        "from": "404block-2020",
        "to": "404block"
    },
    {
        "from": "404kph-2020",
        "to": "404kph"
    },
    {
        "from": "404ms-2020",
        "to": "404ms"
    },
    {
        "from": "404th-floor-2020",
        "to": "404th-floor"
    },
    {
        "from": "4o4-2020",
        "to": "4o4"
    },
    {
        "from": "6174-2024",
        "to": "6174"
    },
    {
        "from": "9-lives-2025",
        "to": "9-lives"
    },
    {
        "from": "a-bad-day-for-frank-2016",
        "to": "a-bad-day-for-frank"
    },
    {
        "from": "a-dark-room",
        "to": "adarkroom"
    },
    {
        "from": "a-dogs-adventure-2023",
        "to": "a-dogs-adventure"
    },
    {
        "from": "a-khan-s-soul-2023",
        "to": "a-khan-s-soul"
    },
    {
        "from": "a-king-s-journey-chapter-3-trapped-poisoned-2017",
        "to": "a-king-s-journey-chapter-3-trapped-poisoned"
    },
    {
        "from": "a-ship-in-time-2019",
        "to": "a-ship-in-time"
    },
    {
        "from": "a-snake-2017",
        "to": "a-snake"
    },
    {
        "from": "a-space-in-the-sun-2021",
        "to": "a-space-in-the-sun"
    },
    {
        "from": "a-tourist-in-paris-2017",
        "to": "a-tourist-in-paris"
    },
    {
        "from": "a-voiding-your-problems-2025",
        "to": "a-voiding-your-problems"
    },
    {
        "from": "a0a-2020",
        "to": "a0a"
    },
    {
        "from": "absorbed-2021",
        "to": "absorbed"
    },
    {
        "from": "admiral-schiffchen-2014",
        "to": "admiral-schiffchen"
    },
    {
        "from": "adopt-a-fire-2020",
        "to": "adopt-a-fire"
    },
    {
        "from": "age-of-the-demigods-2023",
        "to": "age-of-the-demigods"
    },
    {
        "from": "ai-begone-2019",
        "to": "ai-begone"
    },
    {
        "from": "aim-lab-from-hell-2022",
        "to": "aim-lab-from-hell"
    },
    {
        "from": "air-fury-2014",
        "to": "air-fury"
    },
    {
        "from": "airspace-alpha-zulu-2021",
        "to": "airspace-alpha-zulu"
    },
    {
        "from": "al13ycat-2025",
        "to": "al13ycat"
    },
    {
        "from": "alchemist-defence",
        "to": "alchemist-defence-2014"
    },
    {
        "from": "alien-scroll",
        "to": "alien-scroll-2021"
    },
    {
        "from": "alive-n-loaded-2015",
        "to": "alive-n-loaded"
    },
    {
        "from": "all-you-have-to-do-is-dream-2025",
        "to": "all-you-have-to-do-is-dream"
    },
    {
        "from": "alone-in-darkness-2018",
        "to": "alone-in-darkness"
    },
    {
        "from": "alquerque-2023",
        "to": "alquerque"
    },
    {
        "from": "alter-2017",
        "to": "alter"
    },
    {
        "from": "amaz3d-2017",
        "to": "amaz3d"
    },
    {
        "from": "america-offline-2018",
        "to": "america-offline"
    },
    {
        "from": "an-offline-life-2018",
        "to": "an-offline-life"
    },
    {
        "from": "anachronic-2023",
        "to": "anachronic"
    },
    {
        "from": "and-then-it-was-gone-2020",
        "to": "and-then-it-was-gone"
    },
    {
        "from": "angry-cleaning-robot-2018",
        "to": "angry-cleaning-robot"
    },
    {
        "from": "angry-temujin-2023",
        "to": "angry-temujin"
    },
    {
        "from": "ant-space-2021",
        "to": "ant-space"
    },
    {
        "from": "anthority-2017",
        "to": "anthority"
    },
    {
        "from": "anti-paradox-run-2015",
        "to": "anti-paradox-run"
    },
    {
        "from": "anti-virus-2018-2018",
        "to": "anti-virus-2018"
    },
    {
        "from": "ap11-2014",
        "to": "ap11"
    },
    {
        "from": "apex-predator-2022",
        "to": "apex-predator"
    },
    {
        "from": "apollo-13kb-2024",
        "to": "apollo-13kb"
    },
    {
        "from": "archerfire-duet-of-aces-2018",
        "to": "archerfire-duet-of-aces"
    },
    {
        "from": "archery-master-2023",
        "to": "archery-master"
    },
    {
        "from": "area-404-signal-not-found-2020",
        "to": "area-404-signal-not-found"
    },
    {
        "from": "arena-of-glothad-2016",
        "to": "arena-of-glothad"
    },
    {
        "from": "arena013-2013",
        "to": "arena013"
    },
    {
        "from": "arithmetic-hunt-2018",
        "to": "arithmetic-hunt"
    },
    {
        "from": "arkanoid-404-2020",
        "to": "arkanoid-404"
    },
    {
        "from": "ashes-of-ulthar-2025",
        "to": "ashes-of-ulthar"
    },
    {
        "from": "assault-on-city-13-2025",
        "to": "assault-on-city-13"
    },
    {
        "from": "astronaut-in-trouble-2021",
        "to": "astronaut-in-trouble"
    },
    {
        "from": "audio-dash-2018",
        "to": "audio-dash"
    },
    {
        "from": "awkward-turtle-2019",
        "to": "awkward-turtle"
    },
    {
        "from": "azetz-2021",
        "to": "azetz"
    },
    {
        "from": "b-2023",
        "to": "b"
    },
    {
        "from": "back-2-home-2019",
        "to": "back-2-home"
    },
    {
        "from": "back-down-the-tower-2019",
        "to": "back-down-the-tower"
    },
    {
        "from": "back-forth-2019",
        "to": "back-forth"
    },
    {
        "from": "back-from-kooky-island-2019",
        "to": "back-from-kooky-island"
    },
    {
        "from": "back-home-2019",
        "to": "back-home"
    },
    {
        "from": "back-in-dino-2019",
        "to": "back-in-dino"
    },
    {
        "from": "back-read-2019",
        "to": "back-read"
    },
    {
        "from": "back-relax-2019",
        "to": "back-relax"
    },
    {
        "from": "back-to-earth-2019",
        "to": "back-to-earth"
    },
    {
        "from": "back-to-game-2019",
        "to": "back-to-game"
    },
    {
        "from": "back-to-life-2019",
        "to": "back-to-life"
    },
    {
        "from": "back-to-rescue-2019",
        "to": "back-to-rescue"
    },
    {
        "from": "back-to-skull-island-2019",
        "to": "back-to-skull-island"
    },
    {
        "from": "back-to-source-2019",
        "to": "back-to-source"
    },
    {
        "from": "back-to-space-2019",
        "to": "back-to-space"
    },
    {
        "from": "back-to-the-80s-2019",
        "to": "back-to-the-80s"
    },
    {
        "from": "back-to-the-battle-ship-2019",
        "to": "back-to-the-battle-ship"
    },
    {
        "from": "back-to-the-stars-2019",
        "to": "back-to-the-stars"
    },
    {
        "from": "backcountry-2019",
        "to": "backcountry"
    },
    {
        "from": "backflipped-2019",
        "to": "backflipped"
    },
    {
        "from": "backlit-treasure-escape-2019",
        "to": "backlit-treasure-escape"
    },
    {
        "from": "backo-2019",
        "to": "backo"
    },
    {
        "from": "backorder-storehouse-2019",
        "to": "backorder-storehouse"
    },
    {
        "from": "backout-2019",
        "to": "backout"
    },
    {
        "from": "backpack-monsters-2019",
        "to": "backpack-monsters"
    },
    {
        "from": "backshooter-2019",
        "to": "backshooter"
    },
    {
        "from": "backshot-tactics",
        "to": "backshot-tactics-2019"
    },
    {
        "from": "backside-ball-2019",
        "to": "backside-ball"
    },
    {
        "from": "backspace-2019",
        "to": "backspace"
    },
    {
        "from": "backspace-magic-2019",
        "to": "backspace-magic"
    },
    {
        "from": "backsteroid-2019",
        "to": "backsteroid"
    },
    {
        "from": "bad-depot-2013",
        "to": "bad-depot"
    },
    {
        "from": "badluck-butter-chicken-goes-to-outer-space-2024",
        "to": "badluck-butter-chicken-goes-to-outer-space"
    },
    {
        "from": "bakpak-2019",
        "to": "bakpak"
    },
    {
        "from": "balance-2018",
        "to": "balance"
    },
    {
        "from": "balloon-problems-2017",
        "to": "balloon-problems"
    },
    {
        "from": "balls-juggle-2015",
        "to": "balls-juggle"
    },
    {
        "from": "bard-s-fantasy-2020",
        "to": "bard-s-fantasy"
    },
    {
        "from": "barry-in-space-2021",
        "to": "barry-in-space"
    },
    {
        "from": "battle-commander-middle-ages-2023",
        "to": "battle-commander-middle-ages"
    },
    {
        "from": "battle-surge-2017",
        "to": "battle-surge"
    },
    {
        "from": "beat-bricks-2019",
        "to": "beat-bricks"
    },
    {
        "from": "beat-rocks-2021",
        "to": "beat-rocks"
    },
    {
        "from": "beats-not-found-2020",
        "to": "beats-not-found"
    },
    {
        "from": "bee-kind-2022",
        "to": "bee-kind"
    },
    {
        "from": "beef-jezos-space-program-2021",
        "to": "beef-jezos-space-program"
    },
    {
        "from": "behind-the-scenery-2019",
        "to": "behind-the-scenery"
    },
    {
        "from": "bewitched-2023",
        "to": "bewitched"
    },
    {
        "from": "big-fish-2019",
        "to": "big-fish"
    },
    {
        "from": "bike-2025",
        "to": "bike"
    },
    {
        "from": "bird-commander-2-2022",
        "to": "bird-commander-2"
    },
    {
        "from": "bit-butcher-2022",
        "to": "bit-butcher"
    },
    {
        "from": "black-cat-caffee-2025",
        "to": "black-cat-caffee"
    },
    {
        "from": "black-cat-chat-2025",
        "to": "black-cat-chat"
    },
    {
        "from": "black-cat-nine-lives-no-mercy-2025",
        "to": "black-cat-nine-lives-no-mercy"
    },
    {
        "from": "black-cat-on-cybertower-2025",
        "to": "black-cat-on-cybertower"
    },
    {
        "from": "black-cat-potions-2025",
        "to": "black-cat-potions"
    },
    {
        "from": "black-cat-s-rise-2025",
        "to": "black-cat-s-rise"
    },
    {
        "from": "black-cat-shinobi-2025",
        "to": "black-cat-shinobi"
    },
    {
        "from": "black-cat-survivor-2025",
        "to": "black-cat-survivor"
    },
    {
        "from": "black-hat-black-cat-2025",
        "to": "black-hat-black-cat"
    },
    {
        "from": "black-kate-2025",
        "to": "black-kate"
    },
    {
        "from": "blackcat-hacker-2025",
        "to": "blackcat-hacker"
    },
    {
        "from": "blackout-2018",
        "to": "blackout"
    },
    {
        "from": "blacky-returns-home-2025",
        "to": "blacky-returns-home"
    },
    {
        "from": "blast-13-kilobytes",
        "to": "blast-13-kilobytes-2014"
    },
    {
        "from": "blasting-shrapnel",
        "to": "blasting-shrapnel-2018"
    },
    {
        "from": "blib-blupper-2016",
        "to": "blib-blupper"
    },
    {
        "from": "blind-fear-2024",
        "to": "blind-fear"
    },
    {
        "from": "blind-spot-dodge-2015",
        "to": "blind-spot-dodge"
    },
    {
        "from": "blinker-2021",
        "to": "blinker"
    },
    {
        "from": "blue-retro-2023",
        "to": "blue-retro"
    },
    {
        "from": "bo-the-dog-2018",
        "to": "bo-the-dog"
    },
    {
        "from": "boat-racing-404",
        "to": "boat-racing-404-2020"
    },
    {
        "from": "bolos-the-dog-2020",
        "to": "bolos-the-dog"
    },
    {
        "from": "bombroll-2020",
        "to": "bombroll"
    },
    {
        "from": "bombslide-2016",
        "to": "bombslide"
    },
    {
        "from": "boots-and-the-black-cauldron-2025",
        "to": "boots-and-the-black-cauldron"
    },
    {
        "from": "bounce-it-back-2019",
        "to": "bounce-it-back"
    },
    {
        "from": "bounceback-2019",
        "to": "bounceback"
    },
    {
        "from": "bounty-islands-2024",
        "to": "bounty-islands"
    },
    {
        "from": "brave-space-2017",
        "to": "brave-space"
    },
    {
        "from": "bridge-the-gap-2015",
        "to": "bridge-the-gap"
    },
    {
        "from": "bring-the-number-back-2019",
        "to": "bring-the-number-back"
    },
    {
        "from": "bring-your-customers-back-online-2018",
        "to": "bring-your-customers-back-online"
    },
    {
        "from": "brokenspace-2021",
        "to": "brokenspace"
    },
    {
        "from": "bubble-jumper",
        "to": "bubble-jumper-2015"
    },
    {
        "from": "bubble-trap-2016",
        "to": "bubble-trap"
    },
    {
        "from": "buggy-snake-2016",
        "to": "buggy-snake"
    },
    {
        "from": "bunny-lost-2017",
        "to": "bunny-lost"
    },
    {
        "from": "burning-the-plants-2022",
        "to": "burning-the-plants"
    },
    {
        "from": "button-football",
        "to": "button-football-2014"
    },
    {
        "from": "buzzoff-2014",
        "to": "buzzoff"
    },
    {
        "from": "bye-roll-2022",
        "to": "bye-roll"
    },
    {
        "from": "byte-armada-2025",
        "to": "byte-armada"
    },
    {
        "from": "byte-deliver-yourself-2020",
        "to": "byte-deliver-yourself"
    },
    {
        "from": "cable-maze",
        "to": "cable-maze-2018"
    },
    {
        "from": "call-center-mess-2018",
        "to": "call-center-mess"
    },
    {
        "from": "can-t-get-back-2019",
        "to": "can-t-get-back"
    },
    {
        "from": "can-you-hear-me-2018",
        "to": "can-you-hear-me"
    },
    {
        "from": "cannonbolf-2023",
        "to": "cannonbolf"
    },
    {
        "from": "captain-nicebeard-the-reverse-pirate-2015",
        "to": "captain-nicebeard-the-reverse-pirate"
    },
    {
        "from": "captain-reverso-2015",
        "to": "captain-reverso"
    },
    {
        "from": "capturing-souls-on-the-river-of-the-dead-2022",
        "to": "capturing-souls-on-the-river-of-the-dead"
    },
    {
        "from": "car-block-404-2020",
        "to": "car-block-404"
    },
    {
        "from": "carbon-s-kitty-care-2025",
        "to": "carbon-s-kitty-care"
    },
    {
        "from": "cardice-2020",
        "to": "cardice"
    },
    {
        "from": "castaway-2017",
        "to": "castaway"
    },
    {
        "from": "castle-wars-2023",
        "to": "castle-wars"
    },
    {
        "from": "castlefire",
        "to": "castlefire-2023"
    },
    {
        "from": "castlerun-maze",
        "to": "castlerun-maze-2023"
    },
    {
        "from": "cat-apult-2025",
        "to": "cat-apult"
    },
    {
        "from": "cat-astrophe-2025",
        "to": "cat-astrophe"
    },
    {
        "from": "cat-fight-2025",
        "to": "cat-fight"
    },
    {
        "from": "cat-goric-escape-from-the-warp-chamber",
        "to": "cat-goric-escape-from-the-warp-chamber-2021"
    },
    {
        "from": "cat-rooftop-adventure-2025",
        "to": "cat-rooftop-adventure"
    },
    {
        "from": "cat-shooter-ritual-catacombs-2025",
        "to": "cat-shooter-ritual-catacombs"
    },
    {
        "from": "cat-vs-the-world-2025",
        "to": "cat-vs-the-world"
    },
    {
        "from": "catch-the-signal-2018",
        "to": "catch-the-signal"
    },
    {
        "from": "catculus-2025",
        "to": "catculus"
    },
    {
        "from": "cathar-2023",
        "to": "cathar"
    },
    {
        "from": "cathedral-builder-2023",
        "to": "cathedral-builder"
    },
    {
        "from": "catnfish-2025",
        "to": "catnfish"
    },
    {
        "from": "catslap-2025",
        "to": "catslap"
    },
    {
        "from": "cattlost-2017",
        "to": "cattlost"
    },
    {
        "from": "celestial-bodies-2021",
        "to": "celestial-bodies"
    },
    {
        "from": "celestial-lighthouse-2021",
        "to": "celestial-lighthouse"
    },
    {
        "from": "cemetery-2022",
        "to": "cemetery"
    },
    {
        "from": "certified-professional-2018",
        "to": "certified-professional"
    },
    {
        "from": "chains-2018",
        "to": "chains"
    },
    {
        "from": "charming-rainbow-rabbit-2021",
        "to": "charming-rainbow-rabbit"
    },
    {
        "from": "charon-jr-2022",
        "to": "charon-jr"
    },
    {
        "from": "checkmate-2017",
        "to": "checkmate"
    },
    {
        "from": "chess-arena",
        "to": "chess-arena-2022"
    },
    {
        "from": "chesspursuit",
        "to": "chesspursuit-2015"
    },
    {
        "from": "chibi-battlemonsters-2014",
        "to": "chibi-battlemonsters"
    },
    {
        "from": "chicken-on-a-line-2018",
        "to": "chicken-on-a-line"
    },
    {
        "from": "chrono-bomb-2015",
        "to": "chrono-bomb"
    },
    {
        "from": "circle-back-2019",
        "to": "circle-back"
    },
    {
        "from": "clawstruck-2025",
        "to": "clawstruck"
    },
    {
        "from": "clawz-2025",
        "to": "clawz"
    },
    {
        "from": "click-the-four-element-2014",
        "to": "click-the-four-element"
    },
    {
        "from": "clicker-pawry-2025",
        "to": "clicker-pawry"
    },
    {
        "from": "clone-not-found-2020",
        "to": "clone-not-found"
    },
    {
        "from": "code-farm-2020",
        "to": "code-farm"
    },
    {
        "from": "coiner-2019",
        "to": "coiner"
    },
    {
        "from": "color-cat-2025",
        "to": "color-cat"
    },
    {
        "from": "connection-2020",
        "to": "connection"
    },
    {
        "from": "conscious-2017",
        "to": "conscious"
    },
    {
        "from": "constellation-wars",
        "to": "constellation-wars-2021"
    },
    {
        "from": "control-2016",
        "to": "control"
    },
    {
        "from": "cooking-for-skully-2022",
        "to": "cooking-for-skully"
    },
    {
        "from": "cooler-2024",
        "to": "cooler"
    },
    {
        "from": "corrupted-packets-2018",
        "to": "corrupted-packets"
    },
    {
        "from": "cosmic-asteroid-catcher-2021",
        "to": "cosmic-asteroid-catcher"
    },
    {
        "from": "cosmic-shooters",
        "to": "cosmic-shooters-2016"
    },
    {
        "from": "couch-2048-2016",
        "to": "couch-2048"
    },
    {
        "from": "coup-ahoo-2024",
        "to": "coup-ahoo"
    },
    {
        "from": "courage-2024",
        "to": "courage"
    },
    {
        "from": "crafty-cauldron-2025",
        "to": "crafty-cauldron"
    },
    {
        "from": "critter-defense",
        "to": "critter-defense-2013"
    },
    {
        "from": "crusaders-and-their-journeys-2023",
        "to": "crusaders-and-their-journeys"
    },
    {
        "from": "cry-in-the-13th-2024",
        "to": "cry-in-the-13th"
    },
    {
        "from": "cryonics-inc-2022",
        "to": "cryonics-inc"
    },
    {
        "from": "cube-13-2024",
        "to": "cube-13"
    },
    {
        "from": "cube-composer-game",
        "to": "cube-composer"
    },
    {
        "from": "curvilinear-2018",
        "to": "curvilinear"
    },
    {
        "from": "cyber-shmup",
        "to": "cyber-shmup-2016"
    },
    {
        "from": "dante-2022",
        "to": "dante"
    },
    {
        "from": "dante-s-dev-hell-2022",
        "to": "dante-s-dev-hell"
    },
    {
        "from": "dark-light-2020",
        "to": "dark-light"
    },
    {
        "from": "darkest-derelict-2021",
        "to": "darkest-derelict"
    },
    {
        "from": "data-warrior-13kb-limit",
        "to": "data-warrior-13kb-limit-2024"
    },
    {
        "from": "dawn-breaker-2019",
        "to": "dawn-breaker"
    },
    {
        "from": "day-of-the-glitch-2016",
        "to": "day-of-the-glitch"
    },
    {
        "from": "dead-again-2022",
        "to": "dead-again"
    },
    {
        "from": "deadly-affection-2022",
        "to": "deadly-affection"
    },
    {
        "from": "deadly-echo-2022",
        "to": "deadly-echo"
    },
    {
        "from": "deadly-taxi-the-road-of-death-2022",
        "to": "deadly-taxi-the-road-of-death"
    },
    {
        "from": "death-at-the-door-2022",
        "to": "death-at-the-door"
    },
    {
        "from": "death-becomes-her-2022",
        "to": "death-becomes-her"
    },
    {
        "from": "death-game-2022",
        "to": "death-game"
    },
    {
        "from": "death-march-2022",
        "to": "death-march"
    },
    {
        "from": "death-or-gloria-2022",
        "to": "death-or-gloria"
    },
    {
        "from": "death-scythe-2022",
        "to": "death-scythe"
    },
    {
        "from": "death-sea-xiii-2023",
        "to": "death-sea-xiii"
    },
    {
        "from": "death13k-2022",
        "to": "death13k"
    },
    {
        "from": "deathclick-2022",
        "to": "deathclick"
    },
    {
        "from": "deathkeeper-2022",
        "to": "deathkeeper"
    },
    {
        "from": "deathwish-2022",
        "to": "deathwish"
    },
    {
        "from": "debriss-2017",
        "to": "debriss"
    },
    {
        "from": "deck-13-2024",
        "to": "deck-13"
    },
    {
        "from": "deep13-2024",
        "to": "deep13"
    },
    {
        "from": "defense-of-the-13th-city-2023",
        "to": "defense-of-the-13th-city"
    },
    {
        "from": "delete-2020",
        "to": "delete"
    },
    {
        "from": "desert-sim-sh",
        "to": "desert-sim-sh-2020"
    },
    {
        "from": "deserter-2019",
        "to": "deserter"
    },
    {
        "from": "destar-2019",
        "to": "destar"
    },
    {
        "from": "dewdrop-farm-2020",
        "to": "dewdrop-farm"
    },
    {
        "from": "digger-2015",
        "to": "digger"
    },
    {
        "from": "digicrush-2020",
        "to": "digicrush"
    },
    {
        "from": "dimension-13-2024",
        "to": "dimension-13"
    },
    {
        "from": "dinner-for-two-2025",
        "to": "dinner-for-two"
    },
    {
        "from": "disconn3-cted-2018",
        "to": "disconn3-cted"
    },
    {
        "from": "disposition-2015",
        "to": "disposition"
    },
    {
        "from": "dive-and-pick-2020",
        "to": "dive-and-pick"
    },
    {
        "from": "divine-wind-2023",
        "to": "divine-wind"
    },
    {
        "from": "don-t-die-to-ghosts-2022",
        "to": "don-t-die-to-ghosts"
    },
    {
        "from": "don-t-forget-to-feed-the-cat-2025",
        "to": "don-t-forget-to-feed-the-cat"
    },
    {
        "from": "don-t-go-back-2019",
        "to": "don-t-go-back"
    },
    {
        "from": "don-t-look-back-2017",
        "to": "don-t-look-back"
    },
    {
        "from": "don-t-shoot-back",
        "to": "don-t-shoot-back-2019"
    },
    {
        "from": "dont-step-on-thirteen-2024",
        "to": "dont-step-on-thirteen"
    },
    {
        "from": "dottie-back-to-sun-2019",
        "to": "dottie-back-to-sun"
    },
    {
        "from": "dr1v3n-wild-2024",
        "to": "dr1v3n-wild"
    },
    {
        "from": "dragon-simulator-2023",
        "to": "dragon-simulator"
    },
    {
        "from": "drake-s-quest-2015",
        "to": "drake-s-quest"
    },
    {
        "from": "dreaming-of-fire-2014",
        "to": "dreaming-of-fire"
    },
    {
        "from": "duel-of-elements-2014",
        "to": "duel-of-elements"
    },
    {
        "from": "dungeon-of-curse-2024",
        "to": "dungeon-of-curse"
    },
    {
        "from": "dusk-2025",
        "to": "dusk"
    },
    {
        "from": "dutch-dredge-2015",
        "to": "dutch-dredge"
    },
    {
        "from": "dynasty-2023",
        "to": "dynasty"
    },
    {
        "from": "earth-the-orbitless-planet-2017",
        "to": "earth-the-orbitless-planet"
    },
    {
        "from": "eat-my-dust-2019",
        "to": "eat-my-dust"
    },
    {
        "from": "edge-not-found-2020",
        "to": "edge-not-found"
    },
    {
        "from": "electron-life-simulator",
        "to": "electron-life-simulator-2020"
    },
    {
        "from": "elematter-2014",
        "to": "elematter"
    },
    {
        "from": "element-war",
        "to": "element-war-2014"
    },
    {
        "from": "elemental-card-wars",
        "to": "elemental-card-wars-2014"
    },
    {
        "from": "elemental-office-2014",
        "to": "elemental-office"
    },
    {
        "from": "elemental-stone-2014",
        "to": "elemental-stone"
    },
    {
        "from": "elementary-challenges-2020",
        "to": "elementary-challenges"
    },
    {
        "from": "elementium-2014",
        "to": "elementium"
    },
    {
        "from": "elements-craft",
        "to": "elements-craft-2014"
    },
    {
        "from": "emoji-memory-2020",
        "to": "emoji-memory"
    },
    {
        "from": "emoji-swap-2018",
        "to": "emoji-swap"
    },
    {
        "from": "emojiphobia-2024",
        "to": "emojiphobia"
    },
    {
        "from": "enchilada-s-day-off-2025",
        "to": "enchilada-s-day-off"
    },
    {
        "from": "encoded-maze-2019",
        "to": "encoded-maze"
    },
    {
        "from": "encounter-2025",
        "to": "encounter"
    },
    {
        "from": "entangled-2019",
        "to": "entangled"
    },
    {
        "from": "entangolf",
        "to": "entangolf-2024"
    },
    {
        "from": "entitled-2023",
        "to": "entitled"
    },
    {
        "from": "envisionator-2018",
        "to": "envisionator"
    },
    {
        "from": "escape-13th-floor-dungeon-2024",
        "to": "escape-13th-floor-dungeon"
    },
    {
        "from": "escape-from-death-hole-2022",
        "to": "escape-from-death-hole"
    },
    {
        "from": "escape-from-flip-city-2015",
        "to": "escape-from-flip-city"
    },
    {
        "from": "escape-from-hell",
        "to": "escape-from-hell-2017"
    },
    {
        "from": "escape-from-maze-13",
        "to": "escape-from-maze-13-2016"
    },
    {
        "from": "escape-from-planet-xiii",
        "to": "escape-from-planet-xiii-2024"
    },
    {
        "from": "escape-the-pit-2014",
        "to": "escape-the-pit"
    },
    {
        "from": "eugor-2015",
        "to": "eugor"
    },
    {
        "from": "every-alien-loves-404-2020",
        "to": "every-alien-loves-404"
    },
    {
        "from": "evil-wood-2017",
        "to": "evil-wood"
    },
    {
        "from": "exilium-the-fall-of-dominus-2024",
        "to": "exilium-the-fall-of-dominus"
    },
    {
        "from": "exit-2020",
        "to": "exit"
    },
    {
        "from": "exit-the-castle-2023",
        "to": "exit-the-castle"
    },
    {
        "from": "f-stop-2024",
        "to": "f-stop"
    },
    {
        "from": "fall-back-2019-2019",
        "to": "fall-back-2019"
    },
    {
        "from": "fall-down-2022",
        "to": "fall-down"
    },
    {
        "from": "falling-blocks-2015",
        "to": "falling-blocks"
    },
    {
        "from": "falling-down-2015",
        "to": "falling-down"
    },
    {
        "from": "fantastic-monster-chronicles-2015",
        "to": "fantastic-monster-chronicles"
    },
    {
        "from": "far-from-ground-control-2021",
        "to": "far-from-ground-control"
    },
    {
        "from": "fast-way-to-die-2014",
        "to": "fast-way-to-die"
    },
    {
        "from": "fear-the-dark-2017",
        "to": "fear-the-dark"
    },
    {
        "from": "feast-and-courtesans-2023",
        "to": "feast-and-courtesans"
    },
    {
        "from": "feathers-not-found-2020",
        "to": "feathers-not-found"
    },
    {
        "from": "feb-13th-death-s-day-off-2022",
        "to": "feb-13th-death-s-day-off"
    },
    {
        "from": "feed-with-words-2018",
        "to": "feed-with-words"
    },
    {
        "from": "feline-fury-2025",
        "to": "feline-fury"
    },
    {
        "from": "fewa-2014",
        "to": "fewa"
    },
    {
        "from": "fight-back-2019",
        "to": "fight-back"
    },
    {
        "from": "fighter-planes",
        "to": "fighter-planes-2017"
    },
    {
        "from": "filenotfound-2020",
        "to": "filenotfound"
    },
    {
        "from": "filepurge-2021",
        "to": "filepurge"
    },
    {
        "from": "fill-in-4-2013",
        "to": "fill-in-4"
    },
    {
        "from": "fill-the-space-2021",
        "to": "fill-the-space"
    },
    {
        "from": "final-lift-2024",
        "to": "final-lift"
    },
    {
        "from": "find-all-pages-2020",
        "to": "find-all-pages"
    },
    {
        "from": "find-an-exit-2020",
        "to": "find-an-exit"
    },
    {
        "from": "find-it-2017",
        "to": "find-it"
    },
    {
        "from": "find-the-lost-cross-2020",
        "to": "find-the-lost-cross"
    },
    {
        "from": "find-the-papers-2020",
        "to": "find-the-papers"
    },
    {
        "from": "find-the-theme-2020",
        "to": "find-the-theme"
    },
    {
        "from": "finding-echo-2017",
        "to": "finding-echo"
    },
    {
        "from": "finding-precious-2017",
        "to": "finding-precious"
    },
    {
        "from": "finn-the-little-collector-2022",
        "to": "finn-the-little-collector"
    },
    {
        "from": "firelite-2015",
        "to": "firelite"
    },
    {
        "from": "fishing-2025",
        "to": "fishing"
    },
    {
        "from": "flappy-ball-2016",
        "to": "flappy-ball"
    },
    {
        "from": "flappy-bird-game-2020",
        "to": "flappy-bird-game"
    },
    {
        "from": "flight-back-home-2019",
        "to": "flight-back-home"
    },
    {
        "from": "flippy-2015",
        "to": "flippy"
    },
    {
        "from": "floating-2021",
        "to": "floating"
    },
    {
        "from": "flour-oh-flour-2020",
        "to": "flour-oh-flour"
    },
    {
        "from": "for-o-foughr-2020",
        "to": "for-o-foughr"
    },
    {
        "from": "forgetful-god-2020",
        "to": "forgetful-god"
    },
    {
        "from": "forgotten-depths-path-of-the-necromancer-2022",
        "to": "forgotten-depths-path-of-the-necromancer"
    },
    {
        "from": "forklift-simulator-2022-2022",
        "to": "forklift-simulator-2022"
    },
    {
        "from": "forsaken-2017",
        "to": "forsaken"
    },
    {
        "from": "fort-dmin-2023",
        "to": "fort-dmin"
    },
    {
        "from": "fort-knight-2023",
        "to": "fort-knight"
    },
    {
        "from": "found-2020",
        "to": "found"
    },
    {
        "from": "found-bomb-2020",
        "to": "found-bomb"
    },
    {
        "from": "fourfold-2020",
        "to": "fourfold"
    },
    {
        "from": "friend-of-the-fallen-2020",
        "to": "friend-of-the-fallen"
    },
    {
        "from": "fungus-2022",
        "to": "fungus"
    },
    {
        "from": "fx404seconds-2020",
        "to": "fx404seconds"
    },
    {
        "from": "galactic-backfire-2015",
        "to": "galactic-backfire"
    },
    {
        "from": "galactic-winds-ii-the-lost-battle-2017",
        "to": "galactic-winds-ii-the-lost-battle"
    },
    {
        "from": "galaxy-raid-2021",
        "to": "galaxy-raid"
    },
    {
        "from": "get-back-from-robot-city-2019",
        "to": "get-back-from-robot-city"
    },
    {
        "from": "get-jess-back-2019",
        "to": "get-jess-back"
    },
    {
        "from": "get-lost-hombre-2017",
        "to": "get-lost-hombre"
    },
    {
        "from": "get-the-flock-outta-here-2024",
        "to": "get-the-flock-outta-here"
    },
    {
        "from": "ghost-mode-2022",
        "to": "ghost-mode"
    },
    {
        "from": "gib-2018",
        "to": "gib"
    },
    {
        "from": "gibbonacci-2023",
        "to": "gibbonacci"
    },
    {
        "from": "give-me-my-face-back-2016",
        "to": "give-me-my-face-back"
    },
    {
        "from": "glitch-2016",
        "to": "glitch"
    },
    {
        "from": "glitch-buster-2016",
        "to": "glitch-buster"
    },
    {
        "from": "glitch-cube-2016",
        "to": "glitch-cube"
    },
    {
        "from": "glitch-rabbit-2016",
        "to": "glitch-rabbit"
    },
    {
        "from": "glitch-switcher-2016",
        "to": "glitch-switcher"
    },
    {
        "from": "go-back-to-space-2021",
        "to": "go-back-to-space"
    },
    {
        "from": "goblin-tower-13k-2018",
        "to": "goblin-tower-13k"
    },
    {
        "from": "godai-the-five-great-2014",
        "to": "godai-the-five-great"
    },
    {
        "from": "going-home-2020",
        "to": "going-home"
    },
    {
        "from": "golfrog-2024",
        "to": "golfrog"
    },
    {
        "from": "grass-tower-defense-2025",
        "to": "grass-tower-defense"
    },
    {
        "from": "grave-quest-2022",
        "to": "grave-quest"
    },
    {
        "from": "gravepassing-2022",
        "to": "gravepassing"
    },
    {
        "from": "gravity-control-2015",
        "to": "gravity-control"
    },
    {
        "from": "gravity-golf",
        "to": "gravity-golf-2015"
    },
    {
        "from": "greeble-2017",
        "to": "greeble"
    },
    {
        "from": "green-vs-parking-space-2021",
        "to": "green-vs-parking-space"
    },
    {
        "from": "guardian-cat-2025",
        "to": "guardian-cat"
    },
    {
        "from": "gunship13k",
        "to": "gunship13k-2014"
    },
    {
        "from": "hans-fixes-the-internet-2018",
        "to": "hans-fixes-the-internet"
    },
    {
        "from": "happy-birthday-jerry-2025",
        "to": "happy-birthday-jerry"
    },
    {
        "from": "hard-vacuum-recon-2013",
        "to": "hard-vacuum-recon"
    },
    {
        "from": "harold-is-heavy-2023",
        "to": "harold-is-heavy"
    },
    {
        "from": "haun13d-hotel-2024",
        "to": "haun13d-hotel"
    },
    {
        "from": "heart-of-the-gods-2022",
        "to": "heart-of-the-gods"
    },
    {
        "from": "heaven-ascent-2020",
        "to": "heaven-ascent"
    },
    {
        "from": "hel-s-trial-2022",
        "to": "hel-s-trial"
    },
    {
        "from": "hex-crusaders-2023",
        "to": "hex-crusaders"
    },
    {
        "from": "hexgl-game",
        "to": "hexgl"
    },
    {
        "from": "hextris-game",
        "to": "hextris"
    },
    {
        "from": "high-treason-2022",
        "to": "high-treason"
    },
    {
        "from": "highway-404-2020",
        "to": "highway-404"
    },
    {
        "from": "hit-space-to-begin-2021",
        "to": "hit-space-to-begin"
    },
    {
        "from": "holy-knight-2023",
        "to": "holy-knight"
    },
    {
        "from": "horizontal-timing-2016",
        "to": "horizontal-timing"
    },
    {
        "from": "house-not-found-2020",
        "to": "house-not-found"
    },
    {
        "from": "how-i-saved-the-internet-2018",
        "to": "how-i-saved-the-internet"
    },
    {
        "from": "human-not-found-2020",
        "to": "human-not-found"
    },
    {
        "from": "humwin-darbold-2021",
        "to": "humwin-darbold"
    },
    {
        "from": "hungry-cat-2025",
        "to": "hungry-cat"
    },
    {
        "from": "i-am-geoffrey-2015",
        "to": "i-am-geoffrey"
    },
    {
        "from": "i-need-my-space-2021",
        "to": "i-need-my-space"
    },
    {
        "from": "i-ve-been-ghosting-2022",
        "to": "i-ve-been-ghosting"
    },
    {
        "from": "i-ve-lost-my-parents-2017",
        "to": "i-ve-lost-my-parents"
    },
    {
        "from": "i-want-to-google-the-game-2020",
        "to": "i-want-to-google-the-game"
    },
    {
        "from": "ibex-2014",
        "to": "ibex"
    },
    {
        "from": "idle-merchant-guild",
        "to": "idle-merchant-guild-2023"
    },
    {
        "from": "idle-necromancer-2022",
        "to": "idle-necromancer"
    },
    {
        "from": "immunity-collapse-2022",
        "to": "immunity-collapse"
    },
    {
        "from": "in-ascent-2021",
        "to": "in-ascent"
    },
    {
        "from": "in-to-net-cafe-2020",
        "to": "in-to-net-cafe"
    },
    {
        "from": "incurable-2017",
        "to": "incurable"
    },
    {
        "from": "infernal-throne-2022",
        "to": "infernal-throne"
    },
    {
        "from": "information-super-highway-404-2020",
        "to": "information-super-highway-404"
    },
    {
        "from": "inside-cat-2025",
        "to": "inside-cat"
    },
    {
        "from": "inside-the-rect-2018",
        "to": "inside-the-rect"
    },
    {
        "from": "instructions-lost-2017",
        "to": "instructions-lost"
    },
    {
        "from": "interplanetary-transport-system-2021",
        "to": "interplanetary-transport-system"
    },
    {
        "from": "invasion-from-jupiter-in-space-2021",
        "to": "invasion-from-jupiter-in-space"
    },
    {
        "from": "invertagon-2015",
        "to": "invertagon"
    },
    {
        "from": "island-hopper-2017",
        "to": "island-hopper"
    },
    {
        "from": "it-adds-up-2024",
        "to": "it-adds-up"
    },
    {
        "from": "it-comes-in-threes-2022",
        "to": "it-comes-in-threes"
    },
    {
        "from": "it-man-2019",
        "to": "it-man"
    },
    {
        "from": "it-s-raining-boxes-2015",
        "to": "it-s-raining-boxes"
    },
    {
        "from": "jam-champs-404-princess-not-found-2020",
        "to": "jam-champs-404-princess-not-found"
    },
    {
        "from": "jazz-2025",
        "to": "jazz"
    },
    {
        "from": "jet-back-gravity-2019",
        "to": "jet-back-gravity"
    },
    {
        "from": "jewelsback-2019",
        "to": "jewelsback"
    },
    {
        "from": "joe-s-space-2021",
        "to": "joe-s-space"
    },
    {
        "from": "johnny-smiter-iii-2020",
        "to": "johnny-smiter-iii"
    },
    {
        "from": "join-the-cubes-2021",
        "to": "join-the-cubes"
    },
    {
        "from": "jolly-rogier-shipwrecked-2014",
        "to": "jolly-rogier-shipwrecked"
    },
    {
        "from": "jouer-2019",
        "to": "jouer"
    },
    {
        "from": "jump-off-line",
        "to": "jump-off-line-2018"
    },
    {
        "from": "just-another-space-shooter",
        "to": "just-another-space-shooter-2021"
    },
    {
        "from": "keep-calm-2023",
        "to": "keep-calm"
    },
    {
        "from": "keep-me-red-2018",
        "to": "keep-me-red"
    },
    {
        "from": "keep-them-off-the-line-2018",
        "to": "keep-them-off-the-line"
    },
    {
        "from": "keep-white-space-2021",
        "to": "keep-white-space"
    },
    {
        "from": "kfish-2015",
        "to": "kfish"
    },
    {
        "from": "khilji-s-folly-2023",
        "to": "khilji-s-folly"
    },
    {
        "from": "kiki-s-cafe-2025",
        "to": "kiki-s-cafe"
    },
    {
        "from": "kill-9-2022",
        "to": "kill-9"
    },
    {
        "from": "king-longlegs-2024",
        "to": "king-longlegs"
    },
    {
        "from": "kittens-crossing-2025",
        "to": "kittens-crossing"
    },
    {
        "from": "kittens-united-2025",
        "to": "kittens-united"
    },
    {
        "from": "kleptokitty-2025",
        "to": "kleptokitty"
    },
    {
        "from": "knight-2023",
        "to": "knight"
    },
    {
        "from": "knight-dreams-2023",
        "to": "knight-dreams"
    },
    {
        "from": "knights-of-acre-2023",
        "to": "knights-of-acre"
    },
    {
        "from": "knights-quest-2020",
        "to": "knights-quest"
    },
    {
        "from": "kosminenvirtaus-2021",
        "to": "kosminenvirtaus"
    },
    {
        "from": "la-once-2020",
        "to": "la-once"
    },
    {
        "from": "labyrinth-vr-experience-2019",
        "to": "labyrinth-vr-experience"
    },
    {
        "from": "lasergrid",
        "to": "lasergrid-2018"
    },
    {
        "from": "laserpointer-2025",
        "to": "laserpointer"
    },
    {
        "from": "last-moon-bunker-2021",
        "to": "last-moon-bunker"
    },
    {
        "from": "last-viking-2023",
        "to": "last-viking"
    },
    {
        "from": "late-runner-2013",
        "to": "late-runner"
    },
    {
        "from": "learn-to-code-cat-2025",
        "to": "learn-to-code-cat"
    },
    {
        "from": "life-of-blobb-2013",
        "to": "life-of-blobb"
    },
    {
        "from": "little-adventure-of-mr-cat-2025",
        "to": "little-adventure-of-mr-cat"
    },
    {
        "from": "lone-guard-the-software",
        "to": "lone-guard-the-software-2016"
    },
    {
        "from": "lonely-soul-2017",
        "to": "lonely-soul"
    },
    {
        "from": "lord-balsekil-s-lairs-of-bad-luck-2024",
        "to": "lord-balsekil-s-lairs-of-bad-luck"
    },
    {
        "from": "lose-to-win-2015",
        "to": "lose-to-win"
    },
    {
        "from": "lossst-a-snake-in-space-2021",
        "to": "lossst-a-snake-in-space"
    },
    {
        "from": "lost-2017",
        "to": "lost"
    },
    {
        "from": "lost-and-angry-2017",
        "to": "lost-and-angry"
    },
    {
        "from": "lost-beacons-2017",
        "to": "lost-beacons"
    },
    {
        "from": "lost-bricks-2017",
        "to": "lost-bricks"
    },
    {
        "from": "lost-carrots-2017",
        "to": "lost-carrots"
    },
    {
        "from": "lost-characters-2017",
        "to": "lost-characters"
    },
    {
        "from": "lost-city-of-s-2024",
        "to": "lost-city-of-s"
    },
    {
        "from": "lost-connection-2017",
        "to": "lost-connection"
    },
    {
        "from": "lost-in-colors-2017",
        "to": "lost-in-colors"
    },
    {
        "from": "lost-in-guam-2017",
        "to": "lost-in-guam"
    },
    {
        "from": "lost-in-memory",
        "to": "lost-in-memory-2017"
    },
    {
        "from": "lost-in-space-endless-destruction-2020",
        "to": "lost-in-space-endless-destruction"
    },
    {
        "from": "lost-in-the-distance-2021",
        "to": "lost-in-the-distance"
    },
    {
        "from": "lost-in-the-stars-2017",
        "to": "lost-in-the-stars"
    },
    {
        "from": "lost-in-the-woods-2017",
        "to": "lost-in-the-woods"
    },
    {
        "from": "lost-in-the-woods-ascii-style-2017",
        "to": "lost-in-the-woods-ascii-style"
    },
    {
        "from": "lost-in-vim-2017",
        "to": "lost-in-vim"
    },
    {
        "from": "lost-love-2017",
        "to": "lost-love"
    },
    {
        "from": "lost-luggage-2017",
        "to": "lost-luggage"
    },
    {
        "from": "lost-packet-2018",
        "to": "lost-packet"
    },
    {
        "from": "lost-path-2017",
        "to": "lost-path"
    },
    {
        "from": "lost-pixels-2017",
        "to": "lost-pixels"
    },
    {
        "from": "lost-robot-2019",
        "to": "lost-robot"
    },
    {
        "from": "lost-time-2017",
        "to": "lost-time"
    },
    {
        "from": "lost-treasure-2017",
        "to": "lost-treasure"
    },
    {
        "from": "lostinthewoods-2017",
        "to": "lostinthewoods"
    },
    {
        "from": "low-res-party-2016",
        "to": "low-res-party"
    },
    {
        "from": "lucky-charm-2025",
        "to": "lucky-charm"
    },
    {
        "from": "lucky-seeds-2013",
        "to": "lucky-seeds"
    },
    {
        "from": "lucky-streak-2013",
        "to": "lucky-streak"
    },
    {
        "from": "ludo-2017",
        "to": "ludo"
    },
    {
        "from": "lunar-pods-2021",
        "to": "lunar-pods"
    },
    {
        "from": "m13e-2024",
        "to": "m13e"
    },
    {
        "from": "m7-summit-2024",
        "to": "m7-summit"
    },
    {
        "from": "man-on-wire-2018",
        "to": "man-on-wire"
    },
    {
        "from": "mars-short-adventure-2021",
        "to": "mars-short-adventure"
    },
    {
        "from": "master-of-13k-suns-2021",
        "to": "master-of-13k-suns"
    },
    {
        "from": "mavi-2022",
        "to": "mavi"
    },
    {
        "from": "maze-runner-vs-13-2024",
        "to": "maze-runner-vs-13"
    },
    {
        "from": "me-myself-and-i-2017",
        "to": "me-myself-and-i"
    },
    {
        "from": "meadow-2019",
        "to": "meadow"
    },
    {
        "from": "medieval-matchup",
        "to": "medieval-matchup-2023"
    },
    {
        "from": "memorygame-2025",
        "to": "memorygame"
    },
    {
        "from": "meow-mountain-2025",
        "to": "meow-mountain"
    },
    {
        "from": "merchant-of-death-2022",
        "to": "merchant-of-death"
    },
    {
        "from": "mess-my-brain",
        "to": "mess-my-brain-2016"
    },
    {
        "from": "mewnbeams-adventure-2025",
        "to": "mewnbeams-adventure"
    },
    {
        "from": "mewsterpiece-2025",
        "to": "mewsterpiece"
    },
    {
        "from": "midnight-heist-2025",
        "to": "midnight-heist"
    },
    {
        "from": "midnight-paws-2025",
        "to": "midnight-paws"
    },
    {
        "from": "midnight-pizza-temptation-2016",
        "to": "midnight-pizza-temptation"
    },
    {
        "from": "midnight-prowler-2025",
        "to": "midnight-prowler"
    },
    {
        "from": "millennials-2024",
        "to": "millennials"
    },
    {
        "from": "mineroads-2015",
        "to": "mineroads"
    },
    {
        "from": "miss-city-2015",
        "to": "miss-city"
    },
    {
        "from": "miss-fortune-2025",
        "to": "miss-fortune"
    },
    {
        "from": "mission-13-lost-in-space-2017",
        "to": "mission-13-lost-in-space"
    },
    {
        "from": "mission-2014",
        "to": "mission"
    },
    {
        "from": "mitternacht-2022",
        "to": "mitternacht"
    },
    {
        "from": "mongol-march-2023",
        "to": "mongol-march"
    },
    {
        "from": "mongorun-2023",
        "to": "mongorun"
    },
    {
        "from": "moon-buggy-racing",
        "to": "moon-buggy-racing-2021"
    },
    {
        "from": "mor-chess",
        "to": "mor-chess-2025"
    },
    {
        "from": "mor-chess-2-2025",
        "to": "mor-chess-2"
    },
    {
        "from": "moth-2022",
        "to": "moth"
    },
    {
        "from": "move-my-world-2015",
        "to": "move-my-world"
    },
    {
        "from": "mud-bowl-derby-2015",
        "to": "mud-bowl-derby"
    },
    {
        "from": "mulligan-s-island-2018",
        "to": "mulligan-s-island"
    },
    {
        "from": "muri-2017",
        "to": "muri"
    },
    {
        "from": "musa-s-quest-2023",
        "to": "musa-s-quest"
    },
    {
        "from": "national-accident-day-2024",
        "to": "national-accident-day"
    },
    {
        "from": "nbody-2015",
        "to": "nbody"
    },
    {
        "from": "necromancer-s-dungeon-2022",
        "to": "necromancer-s-dungeon"
    },
    {
        "from": "need-find-tribbles-2021",
        "to": "need-find-tribbles"
    },
    {
        "from": "need-some-space-2021",
        "to": "need-some-space"
    },
    {
        "from": "nestling-fears-2021",
        "to": "nestling-fears"
    },
    {
        "from": "network-defense",
        "to": "network-defense-2018"
    },
    {
        "from": "nexus-overload-2016",
        "to": "nexus-overload"
    },
    {
        "from": "night-at-hotel-13-2024",
        "to": "night-at-hotel-13"
    },
    {
        "from": "nigo-s-cave-2013",
        "to": "nigo-s-cave"
    },
    {
        "from": "nika-2015",
        "to": "nika"
    },
    {
        "from": "nilo-2020",
        "to": "nilo"
    },
    {
        "from": "ninja-take-back-2019",
        "to": "ninja-take-back"
    },
    {
        "from": "niwatori-2024",
        "to": "niwatori"
    },
    {
        "from": "no-more-space-in-space-2021",
        "to": "no-more-space-in-space"
    },
    {
        "from": "noble-rivers-2023",
        "to": "noble-rivers"
    },
    {
        "from": "nommon-brothers-2015",
        "to": "nommon-brothers"
    },
    {
        "from": "non-mewtonian-cat-2025",
        "to": "non-mewtonian-cat"
    },
    {
        "from": "norman-the-necromancer-2022",
        "to": "norman-the-necromancer"
    },
    {
        "from": "not-13-2024",
        "to": "not-13"
    },
    {
        "from": "nova-runner-2015",
        "to": "nova-runner"
    },
    {
        "from": "noxious-nebula-2022",
        "to": "noxious-nebula"
    },
    {
        "from": "numerical-error-2019",
        "to": "numerical-error"
    },
    {
        "from": "nyx-felis-and-lampyris-2025",
        "to": "nyx-felis-and-lampyris"
    },
    {
        "from": "off-line-2018",
        "to": "off-line"
    },
    {
        "from": "off-the-line-2018-2018",
        "to": "off-the-line-2018"
    },
    {
        "from": "off-the-lines-2018",
        "to": "off-the-lines"
    },
    {
        "from": "offlab-2018",
        "to": "offlab"
    },
    {
        "from": "offline-mobile-gear-2018",
        "to": "offline-mobile-gear"
    },
    {
        "from": "oggy-s-curse-2025",
        "to": "oggy-s-curse"
    },
    {
        "from": "oh-no-all-the-textures-are-404-2020",
        "to": "oh-no-all-the-textures-are-404"
    },
    {
        "from": "olympic-hide-seek-retrospective-atlanta-1996",
        "to": "olympic-hide-seek-retrospective-atlanta-1996-2020"
    },
    {
        "from": "omega-13k-2016",
        "to": "omega-13k"
    },
    {
        "from": "onamazu-2025",
        "to": "onamazu"
    },
    {
        "from": "one-guard-2023",
        "to": "one-guard"
    },
    {
        "from": "online-2018",
        "to": "online"
    },
    {
        "from": "onoff-2018",
        "to": "onoff"
    },
    {
        "from": "onslaught-arena-game",
        "to": "onslaught-arena"
    },
    {
        "from": "orbital-golfing-2021",
        "to": "orbital-golfing"
    },
    {
        "from": "origin-2013",
        "to": "origin"
    },
    {
        "from": "overforged-2023",
        "to": "overforged"
    },
    {
        "from": "pacific-air-battle-2022",
        "to": "pacific-air-battle"
    },
    {
        "from": "pacific-black-cats-2025",
        "to": "pacific-black-cats"
    },
    {
        "from": "packet-jumpr",
        "to": "packet-jumpr-2020"
    },
    {
        "from": "packet-thief-2018",
        "to": "packet-thief"
    },
    {
        "from": "pandemia-2017",
        "to": "pandemia"
    },
    {
        "from": "paratec-systems-2015",
        "to": "paratec-systems"
    },
    {
        "from": "parlez13k-2018",
        "to": "parlez13k"
    },
    {
        "from": "patchnotes-2016",
        "to": "patchnotes"
    },
    {
        "from": "pawker-2025",
        "to": "pawker"
    },
    {
        "from": "perditus-2017",
        "to": "perditus"
    },
    {
        "from": "pest-control-weasels-2014",
        "to": "pest-control-weasels"
    },
    {
        "from": "pet-a-cat-2025",
        "to": "pet-a-cat"
    },
    {
        "from": "pew-pew-2019",
        "to": "pew-pew"
    },
    {
        "from": "phantomicus-2024",
        "to": "phantomicus"
    },
    {
        "from": "phosphorus-dating-2016",
        "to": "phosphorus-dating"
    },
    {
        "from": "picobuddy-2024",
        "to": "picobuddy"
    },
    {
        "from": "pipe-net-2018",
        "to": "pipe-net"
    },
    {
        "from": "pirates-of-the-glitchy-sea-2016",
        "to": "pirates-of-the-glitchy-sea"
    },
    {
        "from": "pizza-undelivery-2019",
        "to": "pizza-undelivery"
    },
    {
        "from": "planet-404-2020",
        "to": "planet-404"
    },
    {
        "from": "planet-404-that-is-yet-to-be-found-2020",
        "to": "planet-404-that-is-yet-to-be-found"
    },
    {
        "from": "planet-not-found-2020",
        "to": "planet-not-found"
    },
    {
        "from": "planty-2014",
        "to": "planty"
    },
    {
        "from": "play-back-2019",
        "to": "play-back"
    },
    {
        "from": "players-not-found-2020",
        "to": "players-not-found"
    },
    {
        "from": "playing-only-space-key-2021",
        "to": "playing-only-space-key"
    },
    {
        "from": "please-die-2015",
        "to": "please-die"
    },
    {
        "from": "please-do-not-the-cat-2025",
        "to": "please-do-not-the-cat"
    },
    {
        "from": "please-finish-in-13th-place-2024",
        "to": "please-finish-in-13th-place"
    },
    {
        "from": "plunder-survivors-2023",
        "to": "plunder-survivors"
    },
    {
        "from": "plusminus13-2024",
        "to": "plusminus13"
    },
    {
        "from": "poker-mysterio-2025",
        "to": "poker-mysterio"
    },
    {
        "from": "polygone-trust-not-found-2020",
        "to": "polygone-trust-not-found"
    },
    {
        "from": "polylithic-2018",
        "to": "polylithic"
    },
    {
        "from": "popball-2019",
        "to": "popball"
    },
    {
        "from": "portolani-2023",
        "to": "portolani"
    },
    {
        "from": "predecessors-2023",
        "to": "predecessors"
    },
    {
        "from": "prison-escape",
        "to": "prison-escape-2016"
    },
    {
        "from": "prisonri0t-2017",
        "to": "prisonri0t"
    },
    {
        "from": "programmer-quest-2018",
        "to": "programmer-quest"
    },
    {
        "from": "project-panther-2025",
        "to": "project-panther"
    },
    {
        "from": "projection-2019",
        "to": "projection"
    },
    {
        "from": "push-back-2019",
        "to": "push-back"
    },
    {
        "from": "put-back-the-toys-2019",
        "to": "put-back-the-toys"
    },
    {
        "from": "puzzle",
        "to": "puzzle-2025"
    },
    {
        "from": "puzzle-from-hell-2019",
        "to": "puzzle-from-hell"
    },
    {
        "from": "pymm-2022",
        "to": "pymm"
    },
    {
        "from": "qress-sqace-2021",
        "to": "qress-sqace"
    },
    {
        "from": "quick-wins-2019",
        "to": "quick-wins"
    },
    {
        "from": "quintessence-2014",
        "to": "quintessence"
    },
    {
        "from": "quintessential-2014",
        "to": "quintessential"
    },
    {
        "from": "r-e-n-e-g-a-d-e-2016",
        "to": "r-e-n-e-g-a-d-e"
    },
    {
        "from": "r3v3rs3-it-2015",
        "to": "r3v3rs3-it"
    },
    {
        "from": "radiospace-failure-2016",
        "to": "radiospace-failure"
    },
    {
        "from": "radius-raid",
        "to": "radius-raid-2013"
    },
    {
        "from": "raider-of-the-lost-gems",
        "to": "raider-of-the-lost-gems-2017"
    },
    {
        "from": "rain-bow-2018",
        "to": "rain-bow"
    },
    {
        "from": "randomly-lost-2017",
        "to": "randomly-lost"
    },
    {
        "from": "ranger-down-2018",
        "to": "ranger-down"
    },
    {
        "from": "raw-space-2015",
        "to": "raw-space"
    },
    {
        "from": "realm-404-2020",
        "to": "realm-404"
    },
    {
        "from": "rebound-2019",
        "to": "rebound"
    },
    {
        "from": "rec-rec-2018",
        "to": "rec-rec"
    },
    {
        "from": "rectangles-2019",
        "to": "rectangles"
    },
    {
        "from": "reculer-2019",
        "to": "reculer"
    },
    {
        "from": "red-space-2017",
        "to": "red-space"
    },
    {
        "from": "refuel-the-factory-2021",
        "to": "refuel-the-factory"
    },
    {
        "from": "regresso-2019",
        "to": "regresso"
    },
    {
        "from": "reptour-2019",
        "to": "reptour"
    },
    {
        "from": "req-n-res-2020",
        "to": "req-n-res"
    },
    {
        "from": "retro-castlevania-colloseum",
        "to": "retro-castlevania-colloseum-2017"
    },
    {
        "from": "return-2019",
        "to": "return"
    },
    {
        "from": "reunion-2017",
        "to": "reunion"
    },
    {
        "from": "reversal-2015",
        "to": "reversal"
    },
    {
        "from": "reverse-and-try-again-2015",
        "to": "reverse-and-try-again"
    },
    {
        "from": "reverse-g-block-2015",
        "to": "reverse-g-block"
    },
    {
        "from": "reverse-parking-2015",
        "to": "reverse-parking"
    },
    {
        "from": "reverse-td-2015",
        "to": "reverse-td"
    },
    {
        "from": "reversed-2015",
        "to": "reversed"
    },
    {
        "from": "reversed-the-game-2015",
        "to": "reversed-the-game"
    },
    {
        "from": "right-2018",
        "to": "right"
    },
    {
        "from": "rin-the-cat-sorceresses-2025",
        "to": "rin-the-cat-sorceresses"
    },
    {
        "from": "rip-2022",
        "to": "rip"
    },
    {
        "from": "rise-2022",
        "to": "rise"
    },
    {
        "from": "risky-nav-2018",
        "to": "risky-nav"
    },
    {
        "from": "riversed-2015",
        "to": "riversed"
    },
    {
        "from": "road-blocks-2015",
        "to": "road-blocks"
    },
    {
        "from": "road-to-pixel-2016",
        "to": "road-to-pixel"
    },
    {
        "from": "robin-hood-2023",
        "to": "robin-hood"
    },
    {
        "from": "robo-galactic-shooter",
        "to": "robo-galactic-shooter-2018"
    },
    {
        "from": "robot-time-machine-2016",
        "to": "robot-time-machine"
    },
    {
        "from": "robots-txt-2020",
        "to": "robots-txt"
    },
    {
        "from": "rocket-cargo-2021",
        "to": "rocket-cargo"
    },
    {
        "from": "rogue-hoarder-2021",
        "to": "rogue-hoarder"
    },
    {
        "from": "rogue-reversal-2015",
        "to": "rogue-reversal"
    },
    {
        "from": "rogueluck-2013",
        "to": "rogueluck"
    },
    {
        "from": "roll-tanks-2020",
        "to": "roll-tanks"
    },
    {
        "from": "roni-and-kira-2025",
        "to": "roni-and-kira"
    },
    {
        "from": "ror-2020",
        "to": "ror"
    },
    {
        "from": "run-from-the-black-cat-2025",
        "to": "run-from-the-black-cat"
    },
    {
        "from": "run-run-run-2019",
        "to": "run-run-run"
    },
    {
        "from": "runekeeper-2023",
        "to": "runekeeper"
    },
    {
        "from": "running-out-of-space-2021",
        "to": "running-out-of-space"
    },
    {
        "from": "rushletters-2018",
        "to": "rushletters"
    },
    {
        "from": "sabotage-2018",
        "to": "sabotage"
    },
    {
        "from": "sails-2023",
        "to": "sails"
    },
    {
        "from": "salvadoran-reclamation-ms-13-2024",
        "to": "salvadoran-reclamation-ms-13"
    },
    {
        "from": "sand-adder-2019",
        "to": "sand-adder"
    },
    {
        "from": "saptcha-2019",
        "to": "saptcha"
    },
    {
        "from": "save-the-lost-friend-2017",
        "to": "save-the-lost-friend"
    },
    {
        "from": "schrodinger-s-cat-walk-2025",
        "to": "schrodinger-s-cat-walk"
    },
    {
        "from": "sci-fi-alchemy-2021",
        "to": "sci-fi-alchemy"
    },
    {
        "from": "sciara-of-colors-2013",
        "to": "sciara-of-colors"
    },
    {
        "from": "scroll-run-2019",
        "to": "scroll-run"
    },
    {
        "from": "sculpting-done-quick-2020",
        "to": "sculpting-done-quick"
    },
    {
        "from": "search-of-sounds-2017",
        "to": "search-of-sounds"
    },
    {
        "from": "searching-for-04-2020",
        "to": "searching-for-04"
    },
    {
        "from": "seating-space-planner-2021",
        "to": "seating-space-planner"
    },
    {
        "from": "semi-charmed-kind-of-dice-2025",
        "to": "semi-charmed-kind-of-dice"
    },
    {
        "from": "send-the-asteroids-back-2019",
        "to": "send-the-asteroids-back"
    },
    {
        "from": "setlerio-2020",
        "to": "setlerio"
    },
    {
        "from": "shadow-alley-2025",
        "to": "shadow-alley"
    },
    {
        "from": "shadow-of-the-keening-star-2021",
        "to": "shadow-of-the-keening-star"
    },
    {
        "from": "shadow-prowler-2025",
        "to": "shadow-prowler"
    },
    {
        "from": "shadow-s-escape",
        "to": "shadow-s-escape-2025"
    },
    {
        "from": "shadow-survivor-2024",
        "to": "shadow-survivor"
    },
    {
        "from": "shadowflame-2025",
        "to": "shadowflame"
    },
    {
        "from": "shapes-love-numbers-2015",
        "to": "shapes-love-numbers"
    },
    {
        "from": "she-s-lost-2017",
        "to": "she-s-lost"
    },
    {
        "from": "sheltercats-2017",
        "to": "sheltercats"
    },
    {
        "from": "shooooooot-2020",
        "to": "shooooooot"
    },
    {
        "from": "shoot-13-nomsters-2024",
        "to": "shoot-13-nomsters"
    },
    {
        "from": "shooty-alien-game-2020",
        "to": "shooty-alien-game"
    },
    {
        "from": "shooty-ship-13k-2021",
        "to": "shooty-ship-13k"
    },
    {
        "from": "short-circuit-2016",
        "to": "short-circuit"
    },
    {
        "from": "signalmon-2018",
        "to": "signalmon"
    },
    {
        "from": "silent-network-2018",
        "to": "silent-network"
    },
    {
        "from": "simple-construction-2015",
        "to": "simple-construction"
    },
    {
        "from": "singularity-2018",
        "to": "singularity"
    },
    {
        "from": "sir-bruno-s-minnelied-2023",
        "to": "sir-bruno-s-minnelied"
    },
    {
        "from": "skeleathon-2022",
        "to": "skeleathon"
    },
    {
        "from": "slime-n-says-2019",
        "to": "slime-n-says"
    },
    {
        "from": "slip-2021",
        "to": "slip"
    },
    {
        "from": "slipstream-13k-2019",
        "to": "slipstream-13k"
    },
    {
        "from": "snakes-and-ladders-2023",
        "to": "snakes-and-ladders"
    },
    {
        "from": "snap-crack-2013",
        "to": "snap-crack"
    },
    {
        "from": "sniff-your-game-2020",
        "to": "sniff-your-game"
    },
    {
        "from": "soldier-run",
        "to": "soldier-run-2017"
    },
    {
        "from": "sos-2021",
        "to": "sos"
    },
    {
        "from": "soul-jumper",
        "to": "soul-jumper-2022"
    },
    {
        "from": "space-2021",
        "to": "space"
    },
    {
        "from": "space-arcade-2021",
        "to": "space-arcade"
    },
    {
        "from": "space-block-invaders-2021",
        "to": "space-block-invaders"
    },
    {
        "from": "space-capture-2021",
        "to": "space-capture"
    },
    {
        "from": "space-game-2021",
        "to": "space-game"
    },
    {
        "from": "space-gum-2021",
        "to": "space-gum"
    },
    {
        "from": "space-huggers-2021",
        "to": "space-huggers"
    },
    {
        "from": "space-in-space-2021",
        "to": "space-in-space"
    },
    {
        "from": "space-invaders-reimagined",
        "to": "space-invaders-reimagined-2014"
    },
    {
        "from": "space-invasion-simulator-2021",
        "to": "space-invasion-simulator"
    },
    {
        "from": "space-janitor-2021",
        "to": "space-janitor"
    },
    {
        "from": "space-playful-adventures-of-cat-emojis-2021",
        "to": "space-playful-adventures-of-cat-emojis"
    },
    {
        "from": "space-refuel-service-2021",
        "to": "space-refuel-service"
    },
    {
        "from": "space-saver-2021",
        "to": "space-saver"
    },
    {
        "from": "space-station-ordeal-2021",
        "to": "space-station-ordeal"
    },
    {
        "from": "space-tanks-2021",
        "to": "space-tanks"
    },
    {
        "from": "space-trouble-2018",
        "to": "space-trouble"
    },
    {
        "from": "space-wallaby-2021",
        "to": "space-wallaby"
    },
    {
        "from": "space-war-2021",
        "to": "space-war"
    },
    {
        "from": "space4-2021",
        "to": "space4"
    },
    {
        "from": "spacebar-s-space-bar-2021",
        "to": "spacebar-s-space-bar"
    },
    {
        "from": "spacepinball-2021",
        "to": "spacepinball"
    },
    {
        "from": "spaces-in-space-2021",
        "to": "spaces-in-space"
    },
    {
        "from": "spaceship-13k-2021",
        "to": "spaceship-13k"
    },
    {
        "from": "spaceship-wars-13k-2021",
        "to": "spaceship-wars-13k"
    },
    {
        "from": "spaceships",
        "to": "spaceships-2014"
    },
    {
        "from": "spaceshmup",
        "to": "spaceshmup-2018"
    },
    {
        "from": "spacetaxi-2021",
        "to": "spacetaxi"
    },
    {
        "from": "spacew-2021",
        "to": "spacew"
    },
    {
        "from": "spacewalk-2021",
        "to": "spacewalk"
    },
    {
        "from": "spare-me-2014",
        "to": "spare-me"
    },
    {
        "from": "spatial-poker-2021",
        "to": "spatial-poker"
    },
    {
        "from": "spectral-shooter-2022",
        "to": "spectral-shooter"
    },
    {
        "from": "spellcast-away-2014",
        "to": "spellcast-away"
    },
    {
        "from": "splat-paddlers-2017",
        "to": "splat-paddlers"
    },
    {
        "from": "squad-13-2024",
        "to": "squad-13"
    },
    {
        "from": "srtfyl-shoot-rectangles-to-find-your-loot-2021",
        "to": "srtfyl-shoot-rectangles-to-find-your-loot"
    },
    {
        "from": "staccato-2013",
        "to": "staccato"
    },
    {
        "from": "starlink-13kb-game-2021",
        "to": "starlink-13kb-game"
    },
    {
        "from": "start-over-2019",
        "to": "start-over"
    },
    {
        "from": "stay-off-the-red-line-2018",
        "to": "stay-off-the-red-line"
    },
    {
        "from": "stay-off-theline-2018",
        "to": "stay-off-theline"
    },
    {
        "from": "steamshot-13-2024",
        "to": "steamshot-13"
    },
    {
        "from": "steer-clear-2022",
        "to": "steer-clear"
    },
    {
        "from": "stolen-sword-2020",
        "to": "stolen-sword"
    },
    {
        "from": "strata-2014",
        "to": "strata"
    },
    {
        "from": "stray-cat-2025",
        "to": "stray-cat"
    },
    {
        "from": "stronger-2022",
        "to": "stronger"
    },
    {
        "from": "sub13-2024",
        "to": "sub13"
    },
    {
        "from": "sum-it-up-2018",
        "to": "sum-it-up"
    },
    {
        "from": "sunset-stars-2021",
        "to": "sunset-stars"
    },
    {
        "from": "sup3rfr1ght-vr-2024",
        "to": "sup3rfr1ght-vr"
    },
    {
        "from": "super-backpacking-adventure-2019",
        "to": "super-backpacking-adventure"
    },
    {
        "from": "super-benji-2025",
        "to": "super-benji"
    },
    {
        "from": "super-chrono-portal-maker-2016",
        "to": "super-chrono-portal-maker"
    },
    {
        "from": "super-cute-bubble-pets-from-hell-2014",
        "to": "super-cute-bubble-pets-from-hell"
    },
    {
        "from": "super-dragon-rescue-2015",
        "to": "super-dragon-rescue"
    },
    {
        "from": "super-peach-world-2015",
        "to": "super-peach-world"
    },
    {
        "from": "superstition-the-black-cat-game-2025",
        "to": "superstition-the-black-cat-game"
    },
    {
        "from": "swagshot-2019",
        "to": "swagshot"
    },
    {
        "from": "swordbattle-io",
        "to": "swordbattle-io-v1"
    },
    {
        "from": "swords-quills-2023",
        "to": "swords-quills"
    },
    {
        "from": "symmetry-not-found-2020",
        "to": "symmetry-not-found"
    },
    {
        "from": "tangled-2025",
        "to": "tangled"
    },
    {
        "from": "tank-wars-reversal",
        "to": "tank-wars-reversal-2015"
    },
    {
        "from": "templo-mayor-2022",
        "to": "templo-mayor"
    },
    {
        "from": "tendergotchi-2022",
        "to": "tendergotchi"
    },
    {
        "from": "terra-mobilis-2024",
        "to": "terra-mobilis"
    },
    {
        "from": "terraform-2014",
        "to": "terraform"
    },
    {
        "from": "terror-defense-2022",
        "to": "terror-defense"
    },
    {
        "from": "tetris",
        "to": "tetris-2015"
    },
    {
        "from": "tetris-monochrome-2020",
        "to": "tetris-monochrome"
    },
    {
        "from": "tetromigo-2024",
        "to": "tetromigo"
    },
    {
        "from": "that-time-i-tried-running-away-from-space-2021",
        "to": "that-time-i-tried-running-away-from-space"
    },
    {
        "from": "the-13-invaders",
        "to": "the-13-invaders-2024"
    },
    {
        "from": "the-13th-door-2024",
        "to": "the-13th-door"
    },
    {
        "from": "the-adventures-of-captain-callisto-2021",
        "to": "the-adventures-of-captain-callisto"
    },
    {
        "from": "the-almighty-evil-2013",
        "to": "the-almighty-evil"
    },
    {
        "from": "the-anti-poker-protocol-2024",
        "to": "the-anti-poker-protocol"
    },
    {
        "from": "the-baltic-league-2023",
        "to": "the-baltic-league"
    },
    {
        "from": "the-black-cat-s-escape",
        "to": "the-black-cat-s-escape-2025"
    },
    {
        "from": "the-black-cross-cat-2025",
        "to": "the-black-cross-cat"
    },
    {
        "from": "the-book-of-ani-2023",
        "to": "the-book-of-ani"
    },
    {
        "from": "the-cat-jumper",
        "to": "the-cat-jumper-2023"
    },
    {
        "from": "the-chroma-incident-2018",
        "to": "the-chroma-incident"
    },
    {
        "from": "the-circle-masters-2018",
        "to": "the-circle-masters"
    },
    {
        "from": "the-city-without-that-number-2024",
        "to": "the-city-without-that-number"
    },
    {
        "from": "the-colorful-journey-2020",
        "to": "the-colorful-journey"
    },
    {
        "from": "the-colourful-board-2020",
        "to": "the-colourful-board"
    },
    {
        "from": "the-core-2018",
        "to": "the-core"
    },
    {
        "from": "the-curse-of-13-cats-2024",
        "to": "the-curse-of-13-cats"
    },
    {
        "from": "the-dandelion-wars",
        "to": "the-dandelion-wars-2024"
    },
    {
        "from": "the-data-backup-2019",
        "to": "the-data-backup"
    },
    {
        "from": "the-deadly-obstacle-course-2022",
        "to": "the-deadly-obstacle-course"
    },
    {
        "from": "the-demons-13-floors",
        "to": "the-demons-13-floors-2024"
    },
    {
        "from": "the-emerald-serpent-2024",
        "to": "the-emerald-serpent"
    },
    {
        "from": "the-fly-2013",
        "to": "the-fly"
    },
    {
        "from": "the-forgotten-cave-2017",
        "to": "the-forgotten-cave"
    },
    {
        "from": "the-galactic-asteroid-cleanup-mission-2021",
        "to": "the-galactic-asteroid-cleanup-mission"
    },
    {
        "from": "the-great-escape",
        "to": "the-great-escape-2021"
    },
    {
        "from": "the-hidden-death-2022",
        "to": "the-hidden-death"
    },
    {
        "from": "the-king-s-missing-page-2020",
        "to": "the-king-s-missing-page"
    },
    {
        "from": "the-knighting-of-sr-isaac-2023",
        "to": "the-knighting-of-sr-isaac"
    },
    {
        "from": "the-labyrinth-of-death",
        "to": "the-labyrinth-of-death-2022"
    },
    {
        "from": "the-laser-cat-2025",
        "to": "the-laser-cat"
    },
    {
        "from": "the-last-space-bender-2021",
        "to": "the-last-space-bender"
    },
    {
        "from": "the-last-spartan-2020",
        "to": "the-last-spartan"
    },
    {
        "from": "the-lonely-13-2024",
        "to": "the-lonely-13"
    },
    {
        "from": "the-magna-carta-2023",
        "to": "the-magna-carta"
    },
    {
        "from": "the-mail-2018",
        "to": "the-mail"
    },
    {
        "from": "the-martians-are-back-2019",
        "to": "the-martians-are-back"
    },
    {
        "from": "the-mongol-horde-2023",
        "to": "the-mongol-horde"
    },
    {
        "from": "the-ninefold-gambit-2025",
        "to": "the-ninefold-gambit"
    },
    {
        "from": "the-pirates-of-the-wind-2013",
        "to": "the-pirates-of-the-wind"
    },
    {
        "from": "the-raising-fighting-spirits-2022",
        "to": "the-raising-fighting-spirits"
    },
    {
        "from": "the-reapers-tournament-of-destiny-2022",
        "to": "the-reapers-tournament-of-destiny"
    },
    {
        "from": "the-red-square-hates-to-be-online-2018",
        "to": "the-red-square-hates-to-be-online"
    },
    {
        "from": "the-silk-trail-2023",
        "to": "the-silk-trail"
    },
    {
        "from": "the-sixth-prime-2024",
        "to": "the-sixth-prime"
    },
    {
        "from": "the-society-of-multiphobics-2024",
        "to": "the-society-of-multiphobics"
    },
    {
        "from": "the-soldier-2025",
        "to": "the-soldier"
    },
    {
        "from": "the-terror-of-mongolia-2023",
        "to": "the-terror-of-mongolia"
    },
    {
        "from": "the-thirteen-storms-of-divine-wrath-2024",
        "to": "the-thirteen-storms-of-divine-wrath"
    },
    {
        "from": "the-thirteenth-offering-2024",
        "to": "the-thirteenth-offering"
    },
    {
        "from": "the-treasure-of-the-nibelungs-2023",
        "to": "the-treasure-of-the-nibelungs"
    },
    {
        "from": "the-tridecomino-coral-reef-2024",
        "to": "the-tridecomino-coral-reef"
    },
    {
        "from": "the-unseen-network-2020",
        "to": "the-unseen-network"
    },
    {
        "from": "the-value-of-time-2-2022",
        "to": "the-value-of-time-2"
    },
    {
        "from": "the-wandering-wraith-2019",
        "to": "the-wandering-wraith"
    },
    {
        "from": "the-water-tap-game-2015",
        "to": "the-water-tap-game"
    },
    {
        "from": "the-wrong-universe-2017",
        "to": "the-wrong-universe"
    },
    {
        "from": "theo-s-escape",
        "to": "theo-s-escape-2016"
    },
    {
        "from": "there-can-be-only-death-2022",
        "to": "there-can-be-only-death"
    },
    {
        "from": "they-follow-2018",
        "to": "they-follow"
    },
    {
        "from": "they-re-back-2019",
        "to": "they-re-back"
    },
    {
        "from": "thirteen-2024",
        "to": "thirteen"
    },
    {
        "from": "thirteen-minutes-to-space-2024",
        "to": "thirteen-minutes-to-space"
    },
    {
        "from": "thirteen-potions-2023",
        "to": "thirteen-potions"
    },
    {
        "from": "thirteen-truco-2024",
        "to": "thirteen-truco"
    },
    {
        "from": "this-game-has-a-random-title-2018",
        "to": "this-game-has-a-random-title"
    },
    {
        "from": "those-final-seconds-2024",
        "to": "those-final-seconds"
    },
    {
        "from": "tic-tac-woe-2022",
        "to": "tic-tac-woe"
    },
    {
        "from": "tide-of-the-templars-2023",
        "to": "tide-of-the-templars"
    },
    {
        "from": "tile-score-2014",
        "to": "tile-score"
    },
    {
        "from": "time-mit-2015",
        "to": "time-mit"
    },
    {
        "from": "time-runner-2019",
        "to": "time-runner"
    },
    {
        "from": "time-worm-2015",
        "to": "time-worm"
    },
    {
        "from": "tiny-stealth-2015",
        "to": "tiny-stealth"
    },
    {
        "from": "toe-tac-tic-2019",
        "to": "toe-tac-tic"
    },
    {
        "from": "tom-black-cat-2025",
        "to": "tom-black-cat"
    },
    {
        "from": "tonality-2014",
        "to": "tonality"
    },
    {
        "from": "totally-usual-offline-dino-runner-2018",
        "to": "totally-usual-offline-dino-runner"
    },
    {
        "from": "tradewarp",
        "to": "tradewarp-2021"
    },
    {
        "from": "trado-polo-explores-2023",
        "to": "trado-polo-explores"
    },
    {
        "from": "trampofelines-2025",
        "to": "trampofelines"
    },
    {
        "from": "traversor-2019",
        "to": "traversor"
    },
    {
        "from": "treasure-hunt-2016",
        "to": "treasure-hunt"
    },
    {
        "from": "tredici-malefici-2024",
        "to": "tredici-malefici"
    },
    {
        "from": "trench-fisher-2023",
        "to": "trench-fisher"
    },
    {
        "from": "triangle-man-escape-2020",
        "to": "triangle-man-escape"
    },
    {
        "from": "triska-the-ninja-cat",
        "to": "triska-the-ninja-cat-2025"
    },
    {
        "from": "triskaidekagenesis-2024",
        "to": "triskaidekagenesis"
    },
    {
        "from": "triskaidekapotamus-2024",
        "to": "triskaidekapotamus"
    },
    {
        "from": "troposphere-2019",
        "to": "troposphere"
    },
    {
        "from": "try-to-be-not-found-2020",
        "to": "try-to-be-not-found"
    },
    {
        "from": "tut-s-tomb-2022",
        "to": "tut-s-tomb"
    },
    {
        "from": "two-ships-passing-in-the-night-2021",
        "to": "two-ships-passing-in-the-night"
    },
    {
        "from": "typing-test-2025",
        "to": "typing-test"
    },
    {
        "from": "unblock-2024",
        "to": "unblock"
    },
    {
        "from": "unloved-13-2024",
        "to": "unloved-13"
    },
    {
        "from": "v-id-2021",
        "to": "v-id"
    },
    {
        "from": "van-helsing-2022",
        "to": "van-helsing"
    },
    {
        "from": "veda-s-run-2017",
        "to": "veda-s-run"
    },
    {
        "from": "vendredi-2017",
        "to": "vendredi"
    },
    {
        "from": "vernissage-2017",
        "to": "vernissage"
    },
    {
        "from": "vertex-connector-2015",
        "to": "vertex-connector"
    },
    {
        "from": "vier-wizard-wars",
        "to": "vier-wizard-wars-2014"
    },
    {
        "from": "village-not-found-404-to-200-2020",
        "to": "village-not-found-404-to-200"
    },
    {
        "from": "void-2015",
        "to": "void"
    },
    {
        "from": "void-cat-2025",
        "to": "void-cat"
    },
    {
        "from": "volcano-drop-2022",
        "to": "volcano-drop"
    },
    {
        "from": "vote-by-mail-funding-not-found-2020",
        "to": "vote-by-mail-funding-not-found"
    },
    {
        "from": "vr-racing",
        "to": "vr-racing-2017"
    },
    {
        "from": "wake-the-cat-2025",
        "to": "wake-the-cat"
    },
    {
        "from": "wandering-moon-2017",
        "to": "wandering-moon"
    },
    {
        "from": "wandermaze-2014",
        "to": "wandermaze"
    },
    {
        "from": "wands-of-triskaidekai-2024",
        "to": "wands-of-triskaidekai"
    },
    {
        "from": "wanted-2023",
        "to": "wanted"
    },
    {
        "from": "wash-the-cat-2025",
        "to": "wash-the-cat"
    },
    {
        "from": "wasteworld-2022",
        "to": "wasteworld"
    },
    {
        "from": "way-out-2019",
        "to": "way-out"
    },
    {
        "from": "we-must-go-back-2019",
        "to": "we-must-go-back"
    },
    {
        "from": "weird-cannon-2023",
        "to": "weird-cannon"
    },
    {
        "from": "welcome-to-the-cyberspace-2018",
        "to": "welcome-to-the-cyberspace"
    },
    {
        "from": "wendol-village-2024",
        "to": "wendol-village"
    },
    {
        "from": "when-your-neighbors-are-mongols-2023",
        "to": "when-your-neighbors-are-mongols"
    },
    {
        "from": "where-is-winston-2017",
        "to": "where-is-winston"
    },
    {
        "from": "whirled-on-the-spirit-spiral-2018",
        "to": "whirled-on-the-spirit-spiral"
    },
    {
        "from": "whistleblower-2014",
        "to": "whistleblower"
    },
    {
        "from": "whistler-s-motive-2015",
        "to": "whistler-s-motive"
    },
    {
        "from": "whozfast-2017",
        "to": "whozfast"
    },
    {
        "from": "wild-catch-2025",
        "to": "wild-catch"
    },
    {
        "from": "winwin-2020",
        "to": "winwin"
    },
    {
        "from": "wired-2018",
        "to": "wired"
    },
    {
        "from": "witch-hunter-2024",
        "to": "witch-hunter"
    },
    {
        "from": "witch-potion-2025",
        "to": "witch-potion"
    },
    {
        "from": "witchcat-2025",
        "to": "witchcat"
    },
    {
        "from": "wizard-tower-2015",
        "to": "wizard-tower"
    },
    {
        "from": "wizard-with-a-shotgun-2020",
        "to": "wizard-with-a-shotgun"
    },
    {
        "from": "woe-war-of-elements",
        "to": "woe-war-of-elements-2014"
    },
    {
        "from": "wolf-and-sheep-2019",
        "to": "wolf-and-sheep"
    },
    {
        "from": "wolly-is-where-2017",
        "to": "wolly-is-where"
    },
    {
        "from": "wor-2023",
        "to": "wor"
    },
    {
        "from": "world-lost-2017",
        "to": "world-lost"
    },
    {
        "from": "world-of-emojis-2022",
        "to": "world-of-emojis"
    },
    {
        "from": "worms-13k-2025",
        "to": "worms-13k"
    },
    {
        "from": "xiicur-surviivors-2024",
        "to": "xiicur-surviivors"
    },
    {
        "from": "xiii-floor-2024",
        "to": "xiii-floor"
    },
    {
        "from": "xycore-2019",
        "to": "xycore"
    },
    {
        "from": "yellow-and-blue-2022",
        "to": "yellow-and-blue"
    },
    {
        "from": "yet-another-doom-clone-2019",
        "to": "yet-another-doom-clone"
    },
    {
        "from": "yet-another-space-shooter",
        "to": "yet-another-space-shooter-2020"
    },
    {
        "from": "yourspace-2021",
        "to": "yourspace"
    },
    {
        "from": "z0mb13-2024",
        "to": "z0mb13"
    },
    {
        "from": "zabobon-2025",
        "to": "zabobon"
    },
    {
        "from": "zamo-2017",
        "to": "zamo"
    },
    {
        "from": "zero-distraction-2018",
        "to": "zero-distraction"
    },
    {
        "from": "zombie-state-university-munchie-s-late-for-class",
        "to": "zombie-state-university-munchie-s-late-for-class-2022"
    },
    {
        "from": "zombieburger",
        "to": "zombieburger-2019"
    }
];
